# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JRF2jK6bEXoGHZzW60oTcnoo9YeZ5Ph6
"""

print ("Studenti")

studenti = 25

altri_studenti = 3

somma_studenti = studenti + altri_studenti
print (somma_studenti)

spam = [0,1,2,3,4,5]
print (spam)

spam = ['Interstellar', 'Harry Potter', 'Il signore degli anelli']
print (spam)